export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';

export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';

export const SHOW_REGFORM_MESSAGE = 'REGFORM/SHOW_ALERT'
export const HIDE_REGFORM_MESSAGE = 'REGFORM/HIDE_ALERT'

export const FETCH_CATEGORIES = 'CONTROLS/FETCH_CATEGORIES';

export const FETCH_CARDS = 'CARDS/FETCH_CARDS';
export const SHOW_CARDS = 'CARDS/SHOW_CARDS';
export const FETCH_CARD_INFO = 'CARDS/FETCH_CARD_INFO';
export const SET_SIZE = 'CARDS/SET_SIZE';
export const SET_CURRENCY = 'CARDS/SET_CURRENCY';
export const ADD_STAR = 'CARDS/ADD_STAR';
export const REMOVE_STAR = 'CARDS/REMOVE_STAR';

export const SET_LANG = 'STATE/SET_LANG';

export const ADD_TO_SHOPCART = 'CART/ADD_TO_SHOPCART';
export const SET_QUANTITY = 'CART/SET_QUANTITY';
export const REMOVE_FROM_CART = 'CART/REMOVE_FROM_CART';
export const CLEAR_CART = 'CART/CLEAR_CART';

export const LOGIN_USER = 'USER/LOGIN';
export const REGISTER_USER = 'USER/REGISTER';
export const LOGOUT_USER = 'USER/LOGOUT';

export const SET_ORDER = 'ORDER/SET_ORDER';

export const FETCH_ORDERS = 'PROFILE/FETCH_ORDERS';
export const ADD_ORDER = 'PROFILE/ADD_ORDER';
export const REMOVE_ORDER = 'PROFILE/REMOVE_ORDER';
export const SET_NAME = 'PROFILE/SET_NAME';

export const FETCH_WISHES = 'PROFILE/FETCH_WISHES';
export const ADD_TO_WHISHES = 'PROFILE/ADD_TO_WHISHES';
export const REMOVE_FROM_WHISHES = 'PROFILE/REMOVE_FROM_WHISHES';


