export const CREATE_POST = 'POST/CREATE_POST';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';

export const FETCH_CATEGORIES = 'CONTROLS/FETCH_CATEGORIES';
export const FETCH_CARDS = 'CARDS/FETCH_CARDS';
export const SET_COLOR = 'CARDS/SET_COLOR';

export const FETCH_CARD_INFO = 'CARDS/FETCH_CARD_INFO';
export const SET_SIZE = 'CARDS/SET_SIZE';
export const SET_CURRENCY = 'CARDS/SET_CURRENCY'
